// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_YNt-psYQs0Y2FidkHkz01y1ijkIVMEc',
    appId: '1:899331368645:web:96a82d4abe35c7840c72ac',
    messagingSenderId: '899331368645',
    projectId: 'teste-f734e',
    authDomain: 'teste-f734e.firebaseapp.com',
    storageBucket: 'teste-f734e.appspot.com',
    measurementId: 'G-EZSRYPM60Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpeHiL-uyeN2hRx_k5KSEsmMWKtl1Vunk',
    appId: '1:899331368645:android:2c2fd3b57276407c0c72ac',
    messagingSenderId: '899331368645',
    projectId: 'teste-f734e',
    storageBucket: 'teste-f734e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0ieZnALdoyc9mxLyqZcVIsNzRC6rsZJQ',
    appId: '1:899331368645:ios:f1301ce2e625aca60c72ac',
    messagingSenderId: '899331368645',
    projectId: 'teste-f734e',
    storageBucket: 'teste-f734e.appspot.com',
    iosClientId: '899331368645-7l017etb344r25k5ba53qdmhaqetu7of.apps.googleusercontent.com',
    iosBundleId: 'br.com.codigotelas.teste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0ieZnALdoyc9mxLyqZcVIsNzRC6rsZJQ',
    appId: '1:899331368645:ios:f1301ce2e625aca60c72ac',
    messagingSenderId: '899331368645',
    projectId: 'teste-f734e',
    storageBucket: 'teste-f734e.appspot.com',
    iosClientId: '899331368645-7l017etb344r25k5ba53qdmhaqetu7of.apps.googleusercontent.com',
    iosBundleId: 'br.com.codigotelas.teste',
  );
}
